# Generated by Django 6.0.6 on 2026-08-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='applicable_to',
            field=models.CharField(choices=[('IT', 'IT'), ('NON_IT', 'NON_IT'), ('BOTH', 'BOTH')], default='BOTH', max_length=20),
        ),
    ]
