# Generated by Django 6.0.6 on 2026-08-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_applicable_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.IntegerField(default=100, help_text='Number of questions to load in exam')),
                ('exam_duration_minutes', models.IntegerField(default=100, help_text='Exam duration in minutes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam Settings',
                'verbose_name_plural': 'Exam Settings',
            },
        ),
    ]
