# Generated by Django 6.0.6 on 2026-08-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_examsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcategory',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
