# Generated by Django 6.0.6 on 2026-08-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_assessmentcategory_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcategory',
            name='it_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='assessmentcategory',
            name='non_it_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
