# Generated by Django 6.0.6 on 2026-09-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_assessmentcategory_it_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='passout_year',
            field=models.CharField(default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='password',
            field=models.CharField(blank=True, help_text='Temporary field for password migration - will be removed', max_length=255, null=True),
        ),
    ]
