from django.urls import path
from .views import (
    StudentRegisterView,
    StudentLoginView,
    StudentProfileView,
    StudentListView,
    DashboardStatsView,
    RecentActivityView,
    ExamSettingsView,
    ExamSettingsPublicView,
    StudentExamSubmitView,
    StudentExamResultsView,
    DistrictPublicListView,
    DistrictListCreateView,
    DistrictDetailView,
    CollegePublicListView,
    CollegeListCreateView,
    CollegeDetailView,
    CoursePublicListView,
    CourseListCreateView,
    CourseDetailView,
    AssessmentCategoryPublicListView,
    AssessmentCategoryListCreateView,
    AssessmentCategoryDetailView,
    QuestionListCreateView,
    QuestionDetailView,
    QuestionBatchImportView,
    QuestionBatchDeleteView,
    AdminLoginView,
)

urlpatterns = [
    path('admin/login/', AdminLoginView.as_view(), name='admin-login'),
    path('student/register/', StudentRegisterView.as_view(), name='student-register'),
    path('student/login/', StudentLoginView.as_view(), name='student-login'),
    path('student/profile/', StudentProfileView.as_view(), name='student-profile'),
    path('students/', StudentListView.as_view(), name='student-list'),
    path('dashboard/stats/', DashboardStatsView.as_view(), name='dashboard-stats'),
    path('dashboard/recent-activity/', RecentActivityView.as_view(), name='dashboard-recent-activity'),
    path('exam-settings/', ExamSettingsView.as_view(), name='exam-settings'),
    path('public/exam-settings/', ExamSettingsPublicView.as_view(), name='exam-settings-public'),
    path('student/exam/submit/', StudentExamSubmitView.as_view(), name='student-exam-submit'),
    path('student/exam/results/', StudentExamResultsView.as_view(), name='student-exam-results'),
    path('public/districts/', DistrictPublicListView.as_view(), name='district-public'),
    path('public/colleges/', CollegePublicListView.as_view(), name='college-public'),
    path('public/courses/', CoursePublicListView.as_view(), name='course-public'),
    path('public/assessment-categories/', AssessmentCategoryPublicListView.as_view(), name='assessment-category-public'),
    path('districts/', DistrictListCreateView.as_view(), name='district-list-create'),
    path('districts/<int:pk>/', DistrictDetailView.as_view(), name='district-detail'),
    path('colleges/', CollegeListCreateView.as_view(), name='college-list-create'),
    path('colleges/<int:pk>/', CollegeDetailView.as_view(), name='college-detail'),
    path('courses/', CourseListCreateView.as_view(), name='course-list-create'),
    path('courses/<int:pk>/', CourseDetailView.as_view(), name='course-detail'),
    path('assessment-categories/', AssessmentCategoryListCreateView.as_view(), name='assessment-category-list-create'),
    path('assessment-categories/<int:pk>/', AssessmentCategoryDetailView.as_view(), name='assessment-category-detail'),
    path('questions/', QuestionListCreateView.as_view(), name='question-list-create'),
    path('questions/<int:pk>/', QuestionDetailView.as_view(), name='question-detail'),
    path('questions/batch/', QuestionBatchImportView.as_view(), name='question-batch-import'),
    path('questions/batch-delete/', QuestionBatchDeleteView.as_view(), name='question-batch-delete'),
]
